###############################################################################
# consul files
###############################################################################

consul_filename: "\
  {% for asset in assets_files %}\
    {% if asset.name == 'consul' %}\
      asset.filename\
    {% endif %}\
  {% endfor %}"
consul_checksum: "\
  {% for asset in assets_files %}\
    {% if asset.name == 'consul' %}\
      asset.checksum\
    {% endif %}\
  {% endfor %}"

executable: /usr/local/sbin/consul
config_directory: /etc/consul/conf.d
config_data_directory: /var/lib/consul
bcpc_directory: /usr/local/bcpc/bin
chef_databags_config_directory: /chef/databags/config.json

service_ip: "{{ hostvars[inventory_hostname]['interfaces']['service']['ip'] }}"

client_address: 127.0.0.1
consul_dns_port: 8600

scripts:
  - if_leader.j2
  - if_primary_mysql.sh.j2
  - if_not_primary_mysql.sh.j2
  - if_primary_proxysql.sh.j2
  - if_not_primary_proxysql.sh.j2
  - proxysql-check-helper.j2

service_checks:
  - dns-check
  - haproxy-check
  - mysql-check
  - proxysql-check

service_watches:
  - cloud-ip-watch
  - service-elect-watch
  - service-watch

services_interval: 10s
services_timeout: 2s

proxysql_admin_port: 6032
proxysql_port: 6033
myysql_port: 3306