###############################################################################
# consul files
###############################################################################

consul_filename: consul_1.7.2_linux_amd64.zip
consul_checksum: sha256:5ab689cad175c08a226a5c41d16392bc7dd30ceaaf90788411542a756773e698

executable: /usr/local/sbin/consul
config_directory: /etc/consul/conf.d
config_data_directory: /var/lib/consul
bcpc_scripts_directory: /usr/local/bcpc/bin
chef_databags_config_directory: /chef/databags/config.json

service_ip: "{{ hostvars[inventory_hostname]['interfaces']['service']['ip'] }}"

client_address: 127.0.0.1
consul_dns_port: 8600

script_names:
    - if_leader.j2
    - if_primary_mysql.sh.j2
    - if_not_primary_mysql.sh.j2
    - if_primary_proxysql.sh.j2
    - if_not_primary_proxysql.sh.j2
    - proxysql-check-helper.j2

services_interval: 10s
services_timeout: 2s

proxysql_admin_port: 6032
proxysql_port: 6033
myysql_port: 3306