language: generic

os:
  - osx
  - linux

sudo: required
dist: trusty
osx_image: xcode9.4

install: .travis/install-deps.sh

script:
- find . -name "*.sh" -exec shellcheck {} \;
- find . -name "*.sh" -exec bashate {} \;
- find . -name "*.py" -exec flake8 {} \;
- foodcritic chef/cookbooks
- find ansible -name "*.yml" -exec ansible-lint {} \;
