- name: upload chef-client
  copy:
    src: "{{ bcpc.assets.download_dir }}/chef_14.1.1-1_amd64.deb"
    dest: "/tmp/chef_14.1.1-1_amd64.deb"

- name: install chef-client
  apt:
    deb: "/tmp/chef_14.1.1-1_amd64.deb"

- name: create .chef directory
  become: false
  file:
    path: .chef
    state: directory
    mode: 0755

- name: get contents of chef validation key
  shell: |
    cat "/etc/chef/validator.pem"
  register: chef_validation_key
  delegate_to: "{{ bcpc.chef.server.host }}"

- name: install chef validation key
  become: false
  copy:
    dest: "/etc/chef/validator.pem"
    content: "{{ chef_validation_key.stdout }}"

- name: get contents of chef client key
  shell: |
    cat "{{ bcpc.chef.admin.client_key }}"
  register: chef_client_key
  delegate_to: "{{ bcpc.chef.server.host }}"

- name: install chef client key
  become: false
  copy:
    dest: "{{ bcpc.chef.admin.client_key }}"
    content: "{{ chef_client_key.stdout }}"

- name: create .chef/knife.rb
  become: false
  template:
    src: knife.rb.j2
    dest: .chef/knife.rb
    mode: 0600

- name: fetch knife ssl certs
  become: false
  command: knife ssl fetch

- name: create /etc/chef/trusted_certs directory
  file:
    path: /etc/chef/trusted_certs
    state: directory
    mode: 0755

- name: copy chef server ssl certs /etc/chef/trusted_certs
  synchronize:
    src: "/home/{{ operator.username }}/.chef/trusted_certs/"
    dest: /etc/chef/trusted_certs/
  delegate_to: "{{ bcpc.chef.server.host }}"

- name: create chef org directory structure
  become: true
  file:
    state: directory
    path: "/var/bcpc/chef/{{ item }}"
    mode: 0755
    owner: "{{ operator.username }}"
    group: "{{ operator.group }}"
  with_items:
    - "{{ bcpc.chef.org.short_name }}/cookbooks"
    - "{{ bcpc.chef.org.short_name }}/environments"
    - "{{ bcpc.chef.org.short_name }}/databags"
    - "{{ bcpc.chef.org.short_name }}/roles"
    - extra-cookbooks

- name: check for environment databag
  command: knife data bag show "{{ bcpc.chef.environment }}"
  register: databag_check
  failed_when: databag_check.rc != 0
  ignore_errors: true

- name: create environment data bag
  when: databag_check is failed
  shell: |
    knife data bag create "{{ bcpc.chef.environment }}"
