- name: upload cookbooks, environments, roles and databags
  synchronize:
    src: "{{ item }}"
    dest: "/var/bcpc/chef/{{ bcpc.chef.org.short_name }}/"
    recursive: yes
    rsync_opts:
      - '--exclude=*.swp'
  with_items:
    - "{{ bcpc.chef.components.cookbooks.local }}"
    - "{{ bcpc.chef.components.environments }}"
    - "{{ bcpc.chef.components.roles }}"
    - "{{ bcpc.chef.components.databags }}"

- name: upload data bags
  shell: |
    for data_bag in $(ls *.json); do
      knife data bag from file "{{ bcpc.chef.environment }}" ${data_bag}
    done
  args:
    chdir: "/var/bcpc/chef/{{ bcpc.chef.org.short_name }}/databags"

- name: knife upload org
  shell: |
    knife upload .
  args:
    chdir: "/var/bcpc/chef/{{ bcpc.chef.org.short_name }}"
