name: worknode
description: cloud compute services
json_class: Chef::Role
chef_type: role
run_list:
  - role[node]
  - recipe[bcpc::bird]
  - recipe[bcpc::etcd-proxy]
  - recipe[bcpc::calico-work]
  - recipe[bcpc::ceph-osd]
  - recipe[bcpc::nova-compute]
