- name: create web server assets folder
  file:
    path: /var/bcpc/www/files
    state: directory
    mode: 0755
    recurse: true

- include_tasks: upload-web-server-file.yml
  with_items: "{{ all_web_server_assets }}"

- include_tasks: chef-web-server.yml
