- name: set hostname
  hostname:
    name: "{{ node.hostname }}"

- name: update /etc/hosts
  copy:
    dest: /etc/hosts
    content: |
      127.0.0.1	localhost
      127.0.1.1	{{ node.fqdn }}	{{ node.hostname }}
      {{ node.ip }}	{{ node.fqdn }}	{{ node.hostname }}

- name: upload chef-server deb package
  copy:
    src: "{{ bcpc.assets.download_dir }}/chef-server-core_12.17.33-1_amd64.deb"
    dest: "/var/tmp/chef-server-core_12.17.33-1_amd64.deb"

- name: install chef-server deb package
  apt:
    deb: /var/tmp/chef-server-core_12.17.33-1_amd64.deb

- name: configure chef server
  shell: |
    if chef-server-ctl reconfigure; then
      touch /opt/opscode/.reconfigured
    fi
  args:
    creates: /opt/opscode/.reconfigured

- name: create chef server rsa private keys folder
  file:
    path: /etc/chef
    state: directory
    recurse: true

- name: check for association user
  shell: |
    chef-server-ctl \
      user-show "{{ bcpc.chef.admin.username }}"
  register: association_check
  failed_when: association_check.rc != 0
  ignore_errors: true

- name: create chef association user
  when: association_check is failed
  shell: |
    username="{{ bcpc.chef.admin.username }}"
    first_name="{{ bcpc.chef.admin.first_name }}"
    last_name="{{ bcpc.chef.admin.last_name }}"
    email="{{ bcpc.chef.admin.email }}"
    password="{{ bcpc.chef.admin.password }}"
    client_key_file="{{ bcpc.chef.admin.client_key }}"
    user="${username} ${first_name} ${last_name} ${email} ${password}"

    chef-server-ctl user-create ${user} --filename ${client_key_file}

- name: check for organization
  command: chef-server-ctl org-show "{{ bcpc.chef.org.short_name }}"
  register: organization_check
  failed_when: organization_check.rc != 0
  ignore_errors: true

- name: create organization
  when: organization_check is failed
  shell: |
    org_short_name="{{ bcpc.chef.org.short_name }}"
    org_long_name="{{ bcpc.chef.org.long_name }}"

    org="${org_short_name} ${org_long_name}"

    chef-server-ctl org-create ${org} \
      --association_user "{{ bcpc.chef.admin.username }}" \
      --filename "{{ bcpc.chef.org.validator_pem }}"

