# Define Ansible virtualization facts
- name: Define Ansible virtualization facts
  setup:
    gather_subset: "!all,!min,virtual"

# ip_conntrack module configuration and loading
- name: Configure ip_conntrack kernel module when loaded
  template:
    src: system/modprobe.conf.j2
    dest: /etc/modprobe.d/nf_conntrack.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    kernel_module_name: ip_conntrack
    kernel_module_options:
      hashsize: "{{ vars['system_parameters_net.nf_conntrack_max'] // 8 }}"

- name: Load nf_conntrack (ip_conntrack) kernel module
  modprobe:
    name: nf_conntrack

- name: Configure ip_conntrack kernel module hashsize setting
  template:
    src: system/sysfs_variable.j2
    dest: /sys/module/nf_conntrack/parameters/hashsize
    owner: root
    group: root
    mode: '0600'
    unsafe_writes: yes
  vars:
    value: "{{ vars['system_parameters_net.nf_conntrack_max'] // 8 }}"

- name: Ensure ip_conntrack is loaded at boot
  template:
    src: system/modules-load.conf.j2
    dest: /etc/modules-load.d/ip_conntrack.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    kernel_module_name: ip_conntrack

# Configure grub
- name: Configure grub
  template:
    src: grub/default.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  register: grub_defaults

- name: Run update-grub
  command: update-grub
  when: grub_defaults.changed  # noqa no-handler


# Configure sysctl parameters
- name: Configure sysctl parameters
  template:
    src: sysctl/bcpc.conf.j2
    dest: /etc/sysctl.d/70-bcpc.conf
    owner: root
    group: root
    mode: '0644'
  register: sysctl_bcpc

- name: Reload sysctl settings
  command: sysctl -p /etc/sysctl.d/70-bcpc.conf
  when: sysctl_bcpc.changed  # noqa no-handler

# Configure /etc/updatedb.conf
- name: Configure /etc/updatedb.conf
  copy:
    src: files/updatedb/conf
    dest: /etc/updatedb.conf
    owner: root
    group: root
    mode: '0644'

- name: Stop and disable unused services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - accounts-daemon
    - atd
    - fwupd
    - fwupd-refresh
    - irqbalance
    - multipathd.socket
    - multipathd
    - packagekit
    - snapd.socket
    - snapd
    - snapd.seeded
    - udisks2
    - upower
  ignore_errors: yes # noqa ignore-errors

- name: Purge unused service packages
  apt:
    name: "{{ item }}"
    purge: yes
    state: absent
  with_items:
    - accountsservice
    - at
    - fwupd
    - fwupd-signed
    - multipath-tools
    - packagekit
    - packagekit-tools
    - snapd
    - ubuntu-advantage-tools
    - update-notifier-common
    - ubuntu-release-upgrader-core
    - udisks2
    - upower

# Purge off dependencies of uneeded packages
- name: Purge unused packages
  apt:
    autoremove: yes
    purge: yes

# Configure motd-news
- name: Configure motd-news
  template:
    src: system/motd-news.j2
    dest: /etc/default/motd-news
    owner: root
    group: root
    mode: '0644'
  vars:
   enabled: false

# Configure system kernel
- name: Configure system kernel
  apt:
    name: "{{ item }}"
  when: not kernel_pin_version
  with_items:
    - "linux-{{ kernel_variant }}"
    - "linux-tools-{{ kernel_variant }}"

- name: Configure versioned system kernel
  apt:
    name: "{{ item }}"
  when: kernel_pin_version
  with_items:
    - "linux-headers-{{ kernel_version }}-{{ kernel_variant }}"
    - "linux-image-{{ kernel_version }}-{{ kernel_variant }}"
    - "linux-modules-{{ kernel_version }}-{{ kernel_variant }}"
    - "linux-modules-extra-{{ kernel_version }}-{{ kernel_variant }}"
    # HWE kernel-specific tools are pulled in by {{ version }}-generic metapackages.
    - "linux-tools-{{ kernel_version }}-{{ 'generic' if kernel_variant != 'lowlatency' else 'lowlatency' }}"

# bpftool workaround for Jammy systems running Lunar and later kernels:
# Calico 3.26 BPF objects only interop with bpftool linked against libbpf < 1.0
# Lunar kernel tools ship with a bpftool linked against libbpf 1.1, so...
- name: Configure older version of bpftool
  block:
    - name: Install a version of kernel tools that ships with Jammy kernels
      apt:
        name: linux-tools-5.15.0-83-generic

    - name: Symlink the bpftool shim directly to the one from the Jammy kernel
      file:
        src: /usr/lib/linux-tools/5.15.0-83-generic/bpftool
        dest: /usr/sbin/bpftool
        owner: root
        group: root
        state: link
        force: true
  when: kernel_variant == 'generic-hwe-22.04-edge'

# Install kexec-tools
- name: Install kexec-tools
  apt:
    name: kexec-tools

# Configure locale categories
- name: Define locale categories
  set_fact:
    categories: >
      {{
        categories | default('')
        + item.key
        + ('=' + item.value if item.value != '' else '')
      }}
  with_items: "{{ locale_categories | dict2items }}"

- name: Configure locale categories
  command: update-locale {{ categories }}
  changed_when: false
