- name: Include tasks associated with configuring networking
  import_tasks: configure-networking.yml
  become: true
  tags: [never, configure-networking]

- name: Include tasks associated with configuring the installed OS
  import_tasks: configure-system.yml
  become: true
  tags: [never, configure-system]

- name: Include tasks associated with configuring hardware parameters
  import_tasks: configure-hardware.yml
  become: true
  tags: [never, configure-hardware]

- name: Include tasks associated with configuring local block volumes
  import_tasks: configure-volumes.yml
  become: true
  tags: [never, configure-volumes]
