- name: stop, disable and mask systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true

- name: install resolv.conf file
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
