- import_tasks: configure-networking.yml
  become: true
  tags: [never,configure-networking]

- import_tasks: configure-system.yml
  become: true
  tags: [never,configure-system]

- import_tasks: configure-volumes.yml
  become: true
  tags: [never,configure-volumes]
