- name: configure systemd-resolved
  template:
    src: systemd/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  register: resolved

- name: resolv.conf symlink
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  register: resolved

- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
  when: resolved.changed
