- name: Create root's .ssh directory
  file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Set Chef config fact
  set_fact:
    chef_config: "{{ chef_databags
      | selectattr('id', 'equalto', 'config')
      | list
      | first }}"

- name: Configure root's authorized_keys
  copy:
    content: "{{ chef_config['ssh']['public'] | b64decode }}"
    dest: /root/.ssh/authorized_keys
    mode: '0644'

- name: Configure root's private SSH key
  copy:
    content: "{{ chef_config['ssh']['private'] | b64decode }}"
    dest: /root/.ssh/id_ed25519
    mode: '0600'

- name: Configure root's SSH config
  copy:
    content: |
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
    dest: /root/.ssh/config
    mode: '0644'
