- name: install chrony
  apt:
    name: chrony

- name: configure chrony
  template:
    src: chrony/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: 0644
  register: chrony

- name: configure chrony defaults
  template:
    src: chrony/default.j2
    dest: /etc/default/chrony
    mode: 0644
  register: chrony_defaults

- name: create systemd dependency work-around directory for chrony
  file:
    path: /etc/systemd/system/chrony.service.d
    recurse: yes
    state: directory

- name: install service to start monitoring sources after getting a default route
  block:
    - name: install the systemd unit
      copy:
        content: |
          [Unit]
          Description=Wait for default route and bring Chrony sources online
          After=bird.service chrony.service
          Requires=chrony.service

          [Service]
          Type=oneshot
          ExecStart=/bin/sh -c 'while [ -z "$(/sbin/ip route list default)" ]; do sleep 1; done'
          ExecStartPost=/usr/bin/chronyc online
          TimeoutStopSec=1

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/wait-for-default-route.service
        mode: 0644
      register: chrony_custom

    - name: enable the service at reboot
      service:
        name: wait-for-default-route
        daemon_reload: yes
        enabled: yes
      when: chrony_custom.changed

- name: restart chrony
  systemd:
    name: chrony
    state: restarted
  when: chrony.changed or chrony_defaults.changed  # noqa no-handler
