- name: Include tasks associated with defining transit interfaces
  import_tasks: define-transits.yml

- name: Install BIRD
  apt:
    name: bird2

- name: Create /var/log/bird
  file:
    path: /var/log/bird
    state: directory
    group: bird
    owner: bird
    mode: '0755'

- name: Create bird.log with correct permission
  file:
    path: /var/log/bird/bird.log
    state: touch
    group: bird
    owner: bird
    mode: '0644'

- name: Configure BIRD
  template:
    src: bird/bird.conf.j2
    dest: /etc/bird/bird.conf
    mode: '0640'
  register: bird_conf

- name: Reload BIRD
  service:
    name: bird
    state: reloaded
  when: bird_conf.changed # noqa: no-handler

- name: Deploy BIRD logrotate config file
  template:
    src: bird/bird.logrotate
    dest: /etc/logrotate.d/bird
    mode: '0644'

- name: Check for default gateway from TOR
  shell: |
    set -o pipefail
    /usr/sbin/birdc show route | grep 0.0.0.0/0
  args:
    executable: /bin/bash
  retries: 30
  delay: 5
  changed_when: false
  register: result
  until: result.rc == 0
