- import_tasks: define-transits.yml

- name: generate apt preferences for bird2 and dependencies
  template:
    src: bird/apt-preferences.j2
    dest: /etc/apt/preferences.d/98bird
    mode: 0644
  when: ansible_distribution_version == "18.04"

- name: install bird
  apt:
    name: bird2

- name: create /var/log/bird
  file:
    path: /var/log/bird
    state: directory
    group: bird
    owner: bird
    mode: 0755

- name: create bird.log with correct permission
  file:
    path: /var/log/bird/bird.log
    state: touch
    group: bird
    owner: bird
    mode: 0644

- name: configure bird
  template:
    src: bird/bird.conf.j2
    dest: /etc/bird/bird.conf
    mode: 0640
  register: bird_conf

- name: reload bird
  service:
    name: bird
    state: reloaded
  when: bird_conf.changed  # noqa no-handler

- name: deploy bird logrotate config file
  template:
    src: bird/bird.logrotate
    dest: /etc/logrotate.d/bird
    mode: 0644

- name: check for default gateway from tor
  shell: |
    set -o pipefail
    /usr/sbin/birdc show route | grep 0.0.0.0/0
  args:
    executable: /bin/bash
  retries: 30
  delay: 5
  changed_when: false
  register: result
  until: result.rc == 0

- name: add a custom route
  block:
    - name: create custom route systemd unit
      template:
        src: bird/bcc-custom-route.service.j2
        dest: /etc/systemd/system/bcc-custom-route.service
        mode: 0644
      register: bcc_custom_route

    - name: apply custom route
      systemd:
        daemon_reload: true
        enabled: true
        name: bcc-custom-route
        state: restarted
      when: bcc_custom_route.changed  # noqa no-handler
  when: networking.custom_route is defined

- name: delete any custom routes
  block:
    - name: check if custom route service exists
      stat:
        path: /etc/systemd/system/bcc-custom-route.service
      register: route_service_file

    - name: remove custom route
      systemd:
        name: bcc-custom-route
        state: stopped
      when: route_service_file.stat.exists

    - name: delete custom route service
      file:
        path: /etc/systemd/system/bcc-custom-route.service
        state: absent
      when: route_service_file.stat.exists
  when: networking.custom_route is not defined
