- name: gather network and hardware/vm facts
  setup:
    gather_subset: "!all,!min,hardware,network,virtual"

- name: define libvirt_kvm_guest
  set_fact:
    libvirt_kvm_guest: >-
      {{ ansible_virtualization_type == 'kvm'
          and ansible_virtualization_role == 'guest'
          and ansible_system_vendor == 'QEMU' }}

- import_tasks: configure-etc-hosts.yml
  tags: [configure-etc-hosts]

- import_tasks: configure-root-user-ssh.yml
  tags: [configure-root-user-ssh]

- import_tasks: configure-systemd-resolved.yml
  tags: [configure-systemd-resolved]

- import_tasks: configure-local-proxy.yml

- import_tasks: configure-ubuntu-apt-sources.yml
  tags: [configure-ubuntu-apt-sources]

- import_tasks: configure-network-interfaces.yml
  when: configure_network_interfaces | default(true)

- import_tasks: configure-service-ip.yml
  when: configure_service_ip | default(true)

- import_tasks: configure-bgp.yml
  tags: [configure-bgp]

- import_tasks: configure-chrony.yml
  tags: [configure-chrony]

- import_tasks: configure-sshd.yml
