###############################################################################
# configure Unbound
#
# the following section will configure Unbound to be the primary name resolver
###############################################################################

- name: Allow non-local IP binding
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    state: present
  when: "'headnodes' is in group_names"

- name: Install Unbound
  apt:
    name: unbound
    state: present

- name: Remove default Unbound conf files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/unbound/unbound.conf.d/root-auto-trust-anchor-file.conf
  register: unbound_default_conf

- name: Install Unbound default config
  copy:
    src: files/unbound/default
    dest: /etc/default/unbound
    mode: '0644'
  register: unbound_default_conf

- name: Install Unbound server config
  template:
    src: unbound/server.conf.j2
    dest: /etc/unbound/unbound.conf.d/server.conf
    mode: '0644'
  register: unbound_conf

- name: Restart Unbound
  service:
    name: unbound
    state: restarted
  when: unbound_conf.changed or unbound_default_conf.changed

- name: Install /etc/resolv.conf
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: '0644'

###############################################################################
# configure systemd-resolved
#
# the following section will stop, disable and mask the systemd-resolved
# service and revert its configuration
###############################################################################

- name: Stop, disable and mask systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true # noqa: args[module]
