- name: Service IP netdev config
  template:
    src: systemd/network/10-service0.netdev
    dest: /etc/systemd/network/10-service0.netdev
    mode: '0644'
  register: networkd

- name: Service IP network config
  template:
    src: systemd/network/20-service0.network
    dest: /etc/systemd/network/20-service0.network
    mode: '0644'
  register: networkd

- name: Restart systemd-networkd
  service:
    name: systemd-networkd
    state: restarted
  when: networkd.changed # noqa: no-handler
