- import_tasks: configure-etc-hosts.yml
  tags: [configure-etc-hosts]

- name: rename default netplan config
  command: mv /etc/netplan/01-netcfg.yaml /etc/netplan/01-netcfg.yaml.orig
  args:
    removes: /etc/netplan/01-netcfg.yaml
    creates: /etc/netplan/01-netcfg.yaml.orig
  register: netplan

- name: rename default vagrant netplan config
  command: mv /etc/netplan/50-vagrant.yaml /etc/netplan/50-vagrant.yaml.orig
  args:
    removes: /etc/netplan/50-vagrant.yaml
    creates: /etc/netplan/50-vagrant.yaml.orig
  register: netplan

- name: install virtualbox nat interface config
  template:
    src: netplan/virtualbox.yaml.j2
    dest: "/etc/netplan/virtualbox.yaml"
  register: netplan
  when: ansible_virtualization_type == 'virtualbox'

- name: install libvirt nat interface config
  template:
    src: netplan/libvirt.yaml.j2
    dest: "/etc/netplan/libvirt.yaml"
  register: netplan
  when: libvirt_kvm_guest

- name: netplan transit interfaces
  template:
    src: netplan/transit.yaml.j2
    dest: "/etc/netplan/{{ item['name'] }}.yaml"
  with_items:
    "{{ interfaces['transit'] | transit_interfaces(ansible_facts) }}"
  register: netplan

- name: netplan apply
  command: netplan apply
  when: netplan.changed
