- name: Gather network and hardware/vm facts
  setup:
    gather_subset: "!all,!min,hardware,network,virtual"

- name: Define libvirt_kvm_guest
  set_fact:
    libvirt_kvm_guest: >-
      {{ ansible_virtualization_type == 'kvm'
          and ansible_virtualization_role == 'guest'
          and ansible_system_vendor == 'QEMU' }}

- name: Include tasks associated with configuring /etc/hosts
  import_tasks: configure-etc-hosts.yml
  tags: [configure-etc-hosts]

- name: Include tasks associated with configuring network interfaces
  import_tasks: configure-network-interfaces.yml
  tags: [configure_network_interfaces]

- name: Include tasks associated with configuring the service IP
  import_tasks: configure-service-ip.yml
  tags: [configure_service_ip]

- name: Include tasks associated with configuring BGP
  import_tasks: configure-bgp.yml
  tags: [configure-bgp]

- name: Include tasks associated with configuring hostname resolver
  import_tasks: configure-resolver.yml
  tags: [configure-resolver]

- name: Include tasks associated with configuring the local proxy
  import_tasks: configure-local-proxy.yml
  tags: [configure-local-proxy]

- name: Include tasks associated with configuring apt for Ubuntu
  import_tasks: configure-ubuntu-apt-sources.yml
  tags: [configure-ubuntu-apt-sources]

- name: Include tasks associated with configuring NTP
  import_tasks: configure-chrony.yml
  tags: [configure-chrony]

- name: Include tasks associated with configuring the SSH daemon
  import_tasks: configure-sshd.yml
  tags: [configure-sshd]

- name: Include tasks associated with configuring SSH for the root user
  import_tasks: configure-root-user-ssh.yml
  tags: [configure-root-user-ssh]
