- name: Gather host facts for interfaces
  setup:
    gather_subset: "!all,!min,network"

- name: Define transit_interfaces
  set_fact:
    transit_interfaces: >
      {{ interfaces['transit'] | transit_interfaces(ansible_facts) }}
