- name: Include tasks associated with configuring the cloud operator account
  import_tasks: configure-operator.yml
  become: true
  tags: [never, configure-operator]
  when: configure_operator | default(true)

- name: Include tasks associated with setting up Chef client
  import_tasks: chef-client.yml
  become: true
  tags: [never, chef-client]

- name: Include tasks associated with adjusting the PGs in Ceph pools
  import_tasks: adjust-ceph-pool-pgs.yml
  become: true
  run_once: true
  tags: [never, adjust-ceph-pool-pgs]

- name: Include tasks associated with destroying Ceph OSDs
  import_tasks: ceph-destroy-osds.yml
  become: true
  tags: [never, ceph-destroy-osds]

- name: Include tasks associated with reweighting Ceph OSDs
  import_tasks: reweight-ceph-osds.yml
  become: true
  run_once: true
  tags: [never, configure-ceph, reweight-ceph-osds]

- name: Include tasks associated with setting the size of Ceph pools
  import_tasks: set-ceph-pools-size.yml
  become: true
  run_once: true
  tags: [never, configure-ceph, set-ceph-pools-size]

- name: Include tasks associated with configuring the base node information
  import_tasks: configure-node.yml
  become: true
  tags: [never, configure-node]

- name: Include tasks associated with formatting NVMe drives
  import_tasks: format-nvmes.yml
  become: true
  tags: [never, format-nvmes]
