- name: Reweight Ceph OSDs
  changed_when: false
  shell: |
    set -o pipefail
    set -xe

    ceph osd df tree --format json | jq -rc '.nodes[] | \
        select(.type == "osd") | [.id, (.kb / pow(1024;3))]|@tsv' | \
    while IFS=$'\t' read -r id size_tb; do
        ceph osd crush reweight osd.${id} $(printf "%.5f" $size_tb)
    done
  args:
    executable: /bin/bash
