---
- name: query_for_bird_installation
  command: dpkg-query -s bird
  register: dpkg_query_bird
  failed_when: dpkg_query_bird.rc != 0
  ignore_errors: true
  changed_when: false

# Install new bird2 package
- name: Upgrade bird to bird2
  block:
    - name: Check if existing /etc/bird/bird.conf exists
      stat:
        path: /etc/bird/bird.conf
      register: existing_bird_conf

    - name: Backup existing bird config file
      copy:
        remote_src: yes
        src: /etc/bird/bird.conf
        dest: /tmp/bird.conf.old
      when: existing_bird_conf.stat.exists

    - name: Generate apt preferences for bird2 and dependencies
      template:
        src: bird/apt-preferences.j2
        dest: /etc/apt/preferences.d/98bird

    - name: Drop new bird2 config file
      template:
        src: bird/bird.conf.j2
        dest: /tmp/bird.conf.new
        owner: root
        group: root
        mode: 0640

    - name: Download bird2 to apt's package cache
      command:
        cmd: /usr/bin/apt-get install -d -y bird2
        warn: false

    - name: Run upgrade commmands
      shell:
        cmd: |
          systemctl stop bird bird6; \
          apt-get purge -y bird; \
          apt-get install -y bird2; \
          mv /tmp/bird.conf.new /etc/bird/bird.conf; \
          mkdir -p /var/log/bird; \
          touch /var/log/bird/bird.log; \
          chown bird:bird /etc/bird/bird.conf /var/log/bird /var/log/bird/bird.log; \
          systemctl restart bird
        warn: false
      async: 600
      poll: 10

    - name: Remove the backup bird config file
      file:
        path: /tmp/bird.conf.old
        state: absent

  when: dpkg_query_bird is successful
