- name: create assets folder
  file:
    path: "{{ assets_download_dir }}"
    state: directory
    mode: 0764
    recurse: true

- name: download assets
  get_url:
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    dest: "{{ assets_download_dir }}/{{ item.filename }}"
    validate_certs: no
  with_items:
    "{{ assets_files }}"
