- name: generate operations ssh key
  when: ssh.generate_private_key
  become: false
  run_once: true
  delegate_to: localhost
  shell: |
    ssh-keygen -t ed25519 -f "{{ansible_ssh_private_key_file}}" -C '' -N ''
  args:
    creates: "{{ansible_ssh_private_key_file}}"
