- name: Template HAProxy client configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items: "{{ haproxy_client_config_files }}"
  notify: "{{ item.notification }}"
