- name: Include tasks associated with configuring apt for HAProxy
  import_tasks: add-apt-repo.yml
  become: true
  tags: [never, configure-haproxy]
  when: haproxy_repo_enabled

- name: Include tasks associated with installing HAProxy
  import_tasks: install-haproxy.yml
  become: true
  tags: [never, configure-haproxy]

- name: Include tasks associated with configuring HAProxy
  import_tasks: configure-haproxy.yml
  become: true
  tags: [never, configure-haproxy]

- name: Include tasks associated with configuring the clients of HAProxy
  import_tasks: configure-haproxy-clients.yml
  become: true
  tags: [never, configure-haproxy]
