- name: create consul config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - "{{ consul_config_directory }}"
    - "{{ consul_config_data_directory }}"
    - "{{ consul_bcpc_directory }}"

- name: create consul service file systemd
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  notify: restart consul

- name: copy consul scripts
  template:
    src: "{{ item }}"
    dest: "{{ consul_bcpc_directory }}/{{ item.split('.j2')[0] }}"
    owner: root
    group: root
    mode: 0755
  loop: "{{ consul_scripts }}"
  notify: restart consul

- name: copy consul services checks
  copy:
    src: "{{ item }}"
    dest: "{{ consul_bcpc_directory }}"
    owner: root
    group: root
    mode: 0755
  loop: "{{ consul_service_checks }}"

- name: copy consul services watches
  template:
    src: "{{ item }}"
    dest: "{{ consul_bcpc_directory }}"
    owner: root
    group: root
    mode: 0755
  loop: "{{ consul_service_watches }}"

- name: configure consul servers config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - {src: 'services.json.j2', dest: '{{ consul_config_directory }}/services.json'}
    - {src: 'watches.json.j2', dest: '{{ consul_config_directory }}/watches.json'}
    - {src: 'config.json.j2', dest: '{{ consul_config_directory }}/config.json'}
  notify: restart consul

- name: reload systemd
  systemd:
    service: consul.service
    enabled: true
    daemon_reload: yes
  notify: restart consul

- name: force all notified handlers to run at this point
  meta: flush_handlers
