- name: create temp download directory
  tempfile:
    state: directory
    prefix: ansible-consul.
  register: temp_directory

- name: unarchive consul
  unarchive:
    src: "{{ assets_download_dir }}/{{ consul_filename }}"
    dest: "{{ temp_directory.path }}/"
    creates: "{{ temp_directory.path }}/consul"
    mode: 0755

- name: install consul
  copy:
    src: "{{ temp_directory.path }}/consul"
    dest: "{{ consul_executable }}"
    remote_src: yes
    mode: 0755
  notify: restart consul

- name: cleanup temp download directory
  file:
    path: "{{ temp_directory.path }}"
    state: "absent"
