- name: create temp directory
  tempfile:
    state: directory
    prefix: ansible-consul.
  register: temp_directory

- name: unarchive consul
  unarchive:
    src: "{{ assets_download_dir }}/{{ consul_filename }}"
    dest: "{{ temp_directory.path }}/"
    creates: "{{ temp_directory.path }}/consul"
    mode: 0755

- name: install consul
  copy:
    src: "{{ temp_directory.path }}/consul"
    dest: "{{ executable }}"
    remote_src: yes
    mode: 0755
  notify: restart consul

- name: create config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - "{{ config_directory }}"
    - "{{ config_data_directory }}"
    - "{{ bcpc_scripts_directory }}"

- name: create consul service file systemd
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  notify: restart consul

- name: read the Chef databags
  set_fact:
    chef_databags: "{{ lookup('file', (inventory_dir | dirname) + '/chef/databags/config.json') }}"

- name: copy consul scripts
  template:
    src: "{{ item }}"
    dest: "{{ bcpc_scripts_directory }}"
    mode: 0644
  loop: "{{ script_names }}"

- name: reload systemd
  systemd:
    service: consul.service
    enabled: true
    daemon_reload: yes
  notify: restart consul

- name: cleanup
  file:
    path: "{{ temp_directory.path }}"
    state: "absent"
