- hosts: headnodes
  gather_facts: no
  serial: "{{ step | default(ansible_play_batch | length) }}"
  roles:
    - common
    - chef-node
    - cinder
    - glance
    - haproxy
    - headnode
    - heat
    - keystone
    - neutron
    - nova
    - placement
    - watcher
