- hosts: cloud:!bootstraps
  gather_facts: no
  serial: "{{ step | default(ansible_play_batch | length) }}"
  roles:
    - common
    - chef-node

- import_playbook: localhost.yml
- import_playbook: bootstraps.yml
- import_playbook: headnodes.yml
