- name: create roles directory
  file:
    path: "{{ chef_roles_dir }}"
    state: directory
  delegate_to: localhost

- name: import chef roles
  include_vars:
    file: "{{ playbook_dir }}/file_vars/chef/{{ item }}.yml"
    name: "{{ item }}"
  with_items:
    - node
    - bootstrap
    - headnode
    - worknode
    - storagenode

- name: generate chef roles
  template:
    src: "chef-roles/{{ item.role }}.json.j2"
    dest: "{{ chef_roles_dir }}/{{ item.output }}"
  with_items:
    - {role: node, output: node.json}
    - {role: bootstrap, output: bootstrap.json}
    - {role: headnode, output: headnode.json}
    - {role: worknode, output: worknode.json}
    - {role: storagenode, output: storagenode.json}
  delegate_to: localhost
