- name: Upload cookbooks
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "/var/bcpc/chef/{{ chef_org_short_name }}/"
    delete: true
    recursive: true
    rsync_opts:
      - "--copy-links"
      - "--exclude=*.swp"
      - "--exclude=.git"
  with_items:
    - "{{ chef_cookbooks_dir }}"

- name: Upload environments, roles and databags
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "/var/bcpc/chef/{{ chef_org_short_name }}/"
    delete: true
    recursive: true
    rsync_opts:
      - "--exclude=*.swp"
      - "--exclude=.*"
  with_items:
    - "{{ chef_environments_dir }}"
    - "{{ chef_roles_dir }}"
    - "{{ chef_databags_dir }}"

- name: Import config data bag
  command: knife data bag from file "{{ cloud_region }}" config.json
  args:
    chdir: "/var/bcpc/chef/{{ chef_org_short_name }}/databags"
  changed_when: false

- name: Import zones data bag
  command: knife data bag from file "{{ cloud_region }}" zones.json
  args:
    chdir: "/var/bcpc/chef/{{ chef_org_short_name }}/databags"
  changed_when: false

- name: Knife upload org
  command: knife upload .
  args:
    chdir: "/var/bcpc/chef/{{ chef_org_short_name }}"
  changed_when: false
