network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - 10.0.2.15/24
      nameservers:
        addresses:
          - 10.0.2.3
    eth1:
      addresses:
        - 172.16.0.0/31
    eth2:
      addresses:
        - 172.16.0.2/31
    eth3:
      addresses:
        - 192.168.0.1/26
    eth4:
      addresses:
        - 10.121.84.1/28
    eth5:
      addresses:
        - 10.121.88.1/28
