- name: set hostname
  hostname:
    name: "{{ node_hostname }}"

- name: update /etc/hosts
  copy:
    dest: /etc/hosts
    content: |
      127.0.0.1	localhost
      127.0.1.1	{{ node_fqdn }}	{{ node_hostname }}
      {{ node_ip }}	{{ node_fqdn }}	{{ node_hostname }}

- name: upload chef-server deb package
  copy:
    src: "{{ assets_download_dir }}/chef-server-core_12.17.33-1_amd64.deb"
    dest: "/var/tmp/chef-server-core_12.17.33-1_amd64.deb"

- name: install chef-server deb package
  apt:
    deb: /var/tmp/chef-server-core_12.17.33-1_amd64.deb

- name: configure chef server
  shell: |
    if chef-server-ctl reconfigure; then
      touch /opt/opscode/.reconfigured
    fi
  args:
    creates: /opt/opscode/.reconfigured

- name: create chef server rsa private keys folder
  file:
    path: /etc/chef
    state: directory
    recurse: true

- name: check for association user
  command: chef-server-ctl user-show "{{ chef_admin_username }}"
  register: association_check
  failed_when: association_check.rc != 0
  ignore_errors: true
  changed_when: false

- name: create chef association user
  when: association_check is failed
  command: |
    chef-server-ctl user-create \
      '{{ chef_admin_username }}' \
      '{{ chef_admin_first_name }}' \
      '{{ chef_admin_last_name }}' \
      '{{ chef_admin_email }}' \
      '{{ chef_admin_password }}' \
      --filename '{{ chef_admin_client_key }}'

- name: check for organization
  command: chef-server-ctl org-show "{{ chef_org_short_name }}"
  register: organization_check
  failed_when: organization_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: create organization
  when: organization_check is failed
  command: |
    chef-server-ctl org-create \
      '{{ chef_org_short_name }}' \
      '{{ chef_org_long_name }}' \
      --association_user '{{ chef_admin_username }}' \
      --filename '{{ chef_org_validator_pem }}'
