- name: redefine cloud_images var 
  set_fact:
    cloud_images: '{{cloud_images + additional_cloud_images | default([]) }}'

- name: upload cloud images
  copy:
    src: "{{ item.source }}"
    dest: "/var/tmp/"
  with_items:
    "{{ cloud_images }}"

- name: add cloud images
  changed_when: false
  shell: |
    set -x
    source /root/admin-openrc

    if openstack image list | grep -w '{{ item.name }}'; then
      exit 0
    fi

    input='{{ item.input }}'
    output='{{ item.output }}'
    file_ext=${input##*.}

    if [ ${file_ext} = 'xz' ]; then
      unxz $input
      input=${input%.xz}
    fi

    qemu-img convert -f qcow2 -O raw ${input} ${output}

    openstack image create "{{ item.name }}" \
      --public \
      --file ${output}
  args:
    executable: /bin/bash
  with_items:
    "{{ cloud_images }}"
