- name: configuring host aggregates
  shell: |
    aggregate={{ hostvars[item]['aggregate'] }}
    hostname={{ item }}
    zone={{ hostvars[item]['zone'] }}

    if ! openstack aggregate show ${aggregate}; then
        openstack aggregate create ${aggregate} \
            --property network=${zone} \
            --zone ${aggregate}

        openstack aggregate add host ${aggregate} ${hostname}
    fi
  with_items:
    "{{ groups['worknodes'] }}"
  args:
    executable: /bin/bash
  changed_when: false
