- name: capture aggregate list
  command: openstack aggregate list -f json
  register: aggregate_list_json
  changed_when: false

- name: capture compute service list
  command: openstack compute service list --service nova-compute -f json
  register: compute_service_list_json
  changed_when: false

- name: configuring host aggregates
  shell: |
    set -o pipefail

    aggregate={{ hostvars[item]['aggregate'] }}
    hostname={{ item }}
    zone={{ hostvars[item]['zone'] }}

    # create aggregate if it does not exist
    al='{{ aggregate_list_json.stdout }}'

    if ! echo $al | jq -e --arg a $aggregate '.[] | select(.Name == $a)'; then
        openstack aggregate create ${aggregate} \
            --property network=${zone} \
            --zone ${aggregate}
    fi

    # add host to aggregate if it is not a member of one
    csl='{{ compute_service_list_json.stdout }}'

    if echo $csl | jq -e --arg h ${hostname} \
        '.[] | select(.Host == $h and .Zone == "nova")'; then
      openstack aggregate add host ${aggregate} ${hostname}
    fi
  with_items:
    "{{ groups['worknodes'] }}"
  args:
    executable: /bin/bash
  changed_when: false
