- import_tasks: discover-compute-nodes.yml
  become: true
  run_once: true
  tags: [never,discover-compute-nodes]

- import_tasks: glance-images.yml
  become: true
  run_once: true
  tags: [never,glance-images]
