- name: Include tasks associated with registering compute nodes in Nova
  import_tasks: register-compute-nodes.yml
  become: true
  run_once: true
  tags: [never, register-compute-nodes]

- name: Include tasks associated with enabling compute services in Nova
  import_tasks: enable-compute-service.yml
  become: true
  run_once: true
  tags: [never, enable-compute-service]

- name: Include tasks associated with adding images in Glance
  import_tasks: cloud-images.yml
  become: true
  run_once: true
  tags: [never, add-cloud-images]

- name: Include tasks associated with configuring host aggregates in Nova
  import_tasks: configure-host-aggregates.yml
  become: true
  run_once: true
  tags: [never, configure-host-aggregates]

- name: Include tasks associated with configuring licenses in Nova
  import_tasks: configure-licenses.yml
  become: true
  run_once: true
  tags: [never, configure-licenses]
  when: license_traits['enabled']

- name: Include tasks associated with removing licenses in Nova
  import_tasks: remove-licenses.yml
  become: true
  run_once: true
  tags: [never, configure-licenses]
  when: not license_traits['enabled']
