- import_tasks: register-compute-nodes.yml
  become: true
  run_once: true
  tags: [never,register-compute-nodes]

- import_tasks: enable-compute-service.yml
  become: true
  run_once: true
  tags: [never,enable-compute-service]

- import_tasks: cloud-images.yml
  become: true
  run_once: true
  tags: [never,add-cloud-images]

- import_tasks: configure-host-aggregates.yml
  become: true
  run_once: true
  tags: [never,configure-host-aggregates]

- import_tasks: configure-licenses.yml
  become: true
  run_once: true
  tags: [never,configure-licenses]
  when: licenses['enabled']

- import_tasks: remove-licenses.yml
  become: true
  run_once: true
  tags: [never,configure-licenses]
  when: not licenses['enabled']
